version: '2'
services:
    php52mysql:
        image: mysql:5.7
        volumes:
            - "./my.cnf:/etc/mysql/conf.d/my.cnf"
            - "/d/dev/public/database/data/db:/var/lib/mysql"
            - "./sql_dump:/home/sql_dump"
        ports:
            - "3306:3306"    
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: vertrigo
            MYSQL_DATABASE: unimes_docker
            MYSQL_USER: root
            MYSQL_PASSWORD: vertrigo
    php52web:
        volumes:
            - "/d/www/server1:/var/www/html"
        depends_on:
            - php52mysql
        image: sartorifelipe/php5.2
        links:
            - php52mysql
        ports:
            - "8081:80"
        restart: always
        environment:
            DOCUMENT_ROOT: /var/www/html
            ENVIRONMENT: dev