version: '2'
services:
    moodle317-mysql:
        image: mysql:5.7
        volumes:
            - "./my.cnf:/etc/mysql/conf.d/my.cnf"
            - "/d/dev/public/database/data/db_moodle317:/var/lib/mysql"
        ports:
            - "3308:3306"    
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: simples
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
    moodle317-web:
        volumes:
            - "/d/dev/public/moodle/moodle317:/var/www/html"
            - "/d/dev/public/moodledata/moodledata317:/var/www/moodledata"
        depends_on:
            - moodle317-mysql
        image: sartorifelipe/moodle317php
        links:
            - moodle317-mysql
        ports:
            - "8090:80"
        restart: always